# This is a basic workflow to help you get started with Actions

name: eShop deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
    - 'deploy/k8s/helm-simple/coupon/*'
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-aks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrects.AZURE_CREDENTIALS }}
        resource-group: 'eshop-learn-rg'
        cluster-name: 'eshop-learn-aks'
    - name: Get code from repository
      uses: actions/checkout@v1
      with:
        ref: main
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
    - name: Azure login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy
      run: >
        helm upgrade
        --install eshoplearn-coupon
        --namespace=default
        --set registry=${{ secrets.REGISTRY_LOGIN_SERVER }}
        --set imagePullPolicy-Always
        --set host=${{ secrets.IP_ADDRESS }}
        --set protocol=http './deploy/k8s/helm-simple/coupon'
